return PlaceObj('ModDef', {
	'title', "Large_Drone_Station",
	'description', "Compatible with Cernan update (Space Race & Green Planet DLC's)\n\nLarge Drone Station (a remote usage Drone Hub), 3 Hex Building\nSlightly smaller than a Drone Hub but larger than a Recharge Station\n\nCosts;\n6 Concrete\n9 Metals\n4 Polymers\n2 Electronics\n\nMaintenance;\n1 Electronics, but deteriorates slowly\nThe 'Autonomous Hubs' breakthrough will eliminate maintenance, like any standard Drone Hub\n\nProvides;\n10 power when open/on\nDrone Command Range within 12 hexes\nInitial Drones on build (see below)\n\nIncludes 6 different coloured variations and it should respect Colony Colour Schemes\n\nCan be turned on/off individually or en masse\n\nIt has been designed for use at small remote outposts/situations (like the countless amount of Seed Spreaders you might want) or for smaller controlled drone work like shuffling waste rock around, or as an extra task manager in a small radius so you can use it to satisfy local demands with its drones whilst your major hubs organise shuffling resources across your Universal Depots..or to bridge that small gap/oversight in your drone network, instead of building another power guzzling, electric material munching drone hub... the bonus here is that it also that in provides 10 power for whatever remote thing it may be near (like a concrete extractor, concrete depot, waste rock pile setup in the far corners of the map)\n\nStarting Drones;\nInitially comes with 3 drones and can command up to 6\nIF your sponsor is 'SpaceY' you will get an additional bonus drone (4 on build)\nIF you have researched 'Drone Swarm' you will get an additonal bonus drone (4 on build) and max command is increased to 30 (same ratio as for standard Drone Hubs 20>100, or x5)\nIF your sponsor is 'SpaceY' AND you have 'Drone Swarm' researched you will get 3 bonus drones (6 on build) as well as the max command increased to 30\n\nFixes;\nMod contains a fix for Drone Interactions with Drone Hubs and the attached Recharge Stations;\nDrones will now use the other stations at the hub if it is available to charge, or queue at the nearest station of the hub selected\n\nExtras;\nMod contains a custom infopanel designed for the Large Drone Station which includes a version of SkiRich's Toggle Work Zone, idea copied with permission\nOriginal Toggle Work Zone; \nhttps://steamcommunity.com/sharedfiles/filedetails/?id=1436876229 \n\nSpecial Thanks to;\nChoGGi for mod support, code help, fixes and tweaks\nSkiRich for mod support, code help and TWZ permissions\n\nEnjoy !!!",
	'image', "thumbnail.png",
	'last_changes', 'v7 Large update to how the Hex Range rings are handled, should eliminate any spurious range rings on build, open/close, save game. \n\nUpdated how the on/off button functions, I found in playtesting that they really needed to behave like any other building, Left click for single, Ctrl+click for all. It was a silly drawback having them always linked together.\n\nUpdated how they interact with the "Autonomous Hubs" breakthrough. Should now correctly turn off maintenance and update the change in the build menu.\n\n~other~ code fixes and tweaks to provide a better user experience',
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*preview*",
	},
	'id', "XxK6YC",
	'steam_id', "1771215962",
	'pops_desktop_uuid', "bd959cb7-c2b1-449b-a006-042eab323dfb",
	'pops_any_uuid', "1393425d-e042-4b00-a078-17ee834239bc",
	'author', "RustyDios",
	'version_major', 1,
	'version_minor', 7,
	'version', 171,
	'lua_revision', 233360,
	'saved_with_revision', 245618,
	'code', {
		"Code/AddEntities.lua",
		"Code/DroneInteractOverride.lua",
		"Code/Script.lua",
	},
	'saved', 1563305621,
	'screenshot1', "preview.png",
	'screenshot2', "preview2.png",
	'screenshot3', "preview3.png",
	'screenshot4', "preview4.PNG",
	'TagGameplay', true,
	'TagBuildings', true,
	'TagOther', true,
})